# Generated by Django 2.0.4 on 2018-04-16 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingportal', '0004_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='roll_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
