# Generated by Django 2.0.4 on 2018-04-16 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingportal', '0008_auto_20180416_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='entry',
            name='slot',
            field=models.CharField(max_length=10),
        ),
    ]
